### ISSUE TITLE
Sum on realtion

### ISSUE THREAD

**Issue by hairullana** [Alexmg86/laravel-sub-query#12]
Before that I want to write this on discussion repository, but there is not discussion on this repo, so I write this as an issue.

How to sum some field on relation?
I write eloquent from PackingListOrder and the "packing_list_orders" has relation to "order", and then "order" has relation to "items".
On item table, there is field named "picked" & "missing". I need data with the sum of that field, How laravel-sub-query handle this?
![image](https://user-images.githubusercontent.com/56705867/215660849-ba740ee3-9fc0-4a4f-8f35-155f2982386b.png)

I have error message like this
![image](https://user-images.githubusercontent.com/56705867/215661186-08b84789-af48-4b8f-9e62-8c555967a991.png)

**Comment by Alexmg86** [comment]
Hi, @hairullana 
try to add trait in order model and use something like this

```php
$pl_orders = PackingListOrder::where('packing_list_id', $p1->id)
->with(['order' => function ($query) {
    $query->with(['customer', 'country', 'items'])
    ->withSum('items:picked,missing');
}])->get();
```

**Comment by hairullana** [comment]
> Hi, @hairullana try to add trait in order model and use something like this
> 
> ```
> $pl_orders = PackingListOrder::where('packing_list_id', $p1->id)
> ->with(['order' => function ($query) {
>     $query->with(['customer', 'country', 'items'])
>     ->withSum('items:picked,missing');
> }])->get();
> ```

Thank you, it's working
