### ISSUE TITLE
Rememberable package — Trait method 'newBaseQueryBuilder' will not be applied because it collides with 'LaravelSubQueryTrait'

### ISSUE THREAD

**Issue by DanielSpravtsev** [Alexmg86/laravel-sub-query#13]
When adding Rememberable trait to eloquent model with LaravelSubQueryTrait applied:
```
Trait method 'newBaseQueryBuilder' will not be applied because it collides with 'LaravelSubQueryTrait'
```

**Comment by DanielSpravtsev** [comment]
@Alexmg86 Any thoughts how to fix or bypass it?

**Comment by Alexmg86** [comment]
у вас в модели явно подключен какой-то еще трейт и он скорее всего использует newBaseQueryBuilder.
это особенность php и трейтов, что они вызывают конфликты. тут нужно что-то одно выбирать тогда
