### ISSUE TITLE
withSum returns string instead of number

### ISSUE THREAD

**Issue by HugoHeneault** [Alexmg86/laravel-sub-query#4]
Hi there! Thanks for your great package.

When using `::withSum` I'm getting a String value instead of a Number one. Any ideas?

Thanks a lot! 👍

**Comment by Alexmg86** [comment]
Hello!
yes, I think I will be able to add such an opportunity in the near future

**Comment by Alexmg86** [comment]
Hi!
I added this feature in the latest version 1.9.4. The resulting value can be casting through the third parameter.
```php
Invoice::withSum('items:price:signed')->get();
```

**Comment by HugoHeneault** [comment]
Awesome! Thanks! 👏
