### ISSUE TITLE
Where statement in a sum

### ISSUE THREAD

**Issue by jayceedaily** [Alexmg86/laravel-sub-query#5]
Hi Alex.

Been using this for a few days now. Was wondering if its possible to use this to build a `where sum of relationship is equal to` query and how would it be done?

```
class Books {
 public class categories()
  {
   return $this->hasMany(Categories::class);
  }
}
```

```
// Query something like this
$booksWithFiveCategories = Book::withSum('categories')->where('sum_of_categories', 5)->get()
```

**Comment by Alexmg86** [comment]
@jayceedaily, Hi!
the withSum method works to summarize a specific column from the relation (not to be confused with count), in your case categories
```php
$books = Book::withSum('categories:column')->get();
```
If you just want to get books that have 5 categories, then it's better to use [the "has" method ](https://laravel.com/docs/6.x/eloquent-relationships#querying-relationship-existence)
```php
$booksWithFiveCategories = Book::has('categories', 5)->get();
```
I hope I understand you correctly :)

**Comment by jayceedaily** [comment]
Hi alex, thanks for the response. My example was too vague. What I was trying to achieve was more of getting a record if the relationship has a sum of X. Is this possible?

Example:
`
Transaction::withSum('items.price')->where('sum_of_item', '>', 100)->get();`

**Comment by Alexmg86** [comment]
Hi! No, because this field appears only after all data has been processed. And already they can be filtered as collections
