### ISSUE TITLE
LaravelSubQueryCache - Undefined property concats

### ISSUE THREAD

**Issue by bernardotavares** [Alexmg86/laravel-sub-query#6]
Hey, great package!

I has been working for me but after upgrading the OctoberCMS to build 1.1.0 (that uses laravel 6.0 instead of 5.5) I am getting the following error:
`Undefined property: Alexmg86\LaravelSubQuery\LaravelSubQueryCache::$concats`

It seems that $query->concats fails at
\vendor\october\rain\src\Database\Query\Grammars\Concerns\SelectConcatenations.php line 22
This happens when using any model that has the LaravelSubQueryTrait.

**alexmg86/laravel-sub-query:** v1.9.4
**octobercms:** build 471
**laravel:** v6.20.13
**php:** 7.2.25

Any idea of how to approach this?

**Comment by bernardotavares** [comment]
The user "paishin" had a very similar issue with LaravelMysqlSpatial and OctoberCMS.
[issue @ october](https://github.com/octobercms/october/issues/5372)
[issue @ LaravelMysqlSpatial](https://github.com/grimzy/laravel-mysql-spatial/issues/94)

It seems that OctoberCMS is using a custom Query Builder that extends Builder and laravel-sub-query is bypassing it.

Would it be possible for laravel-sub-query identify the correct query builder of the model? Or any other ideas?

**Comment by Alexmg86** [comment]
Hi! I have no idea about this. Because both packages reuse the newBaseQueryBuilder method, and it turns out that only one will work correctly.
