### ISSUE TITLE
Laravel 8.26 Incompatibility issue with Eloquent\Model

### ISSUE THREAD

**Issue by ellalderton** [Alexmg86/laravel-sub-query#8]
Updated to Laravel 8.26.1 and I'm getting incompatibility issue with Eloquent\Model.

Declaration of Alexmg86\LaravelSubQuery\Traits\LaravelSubQueryTrait::loadSum($relations) should be compatible with Illuminate\Database\Eloquent\Model::loadSum($relations, $column)

**Comment by Alexmg86** [comment]
Hi! this method nice working with Laravel version <8, because in new version 8.* already has [this method](https://laravel.com/api/8.x/Illuminate/Database/Eloquent/Model.html#method_loadSum)

**Comment by ellalderton** [comment]
That's great, thanks for your help.

**Comment by joecip** [comment]
@Alexmg86  How do you get around this error? I'd prefer to use LaravelSubQuery's version since it allows for more options.

**Comment by Alexmg86** [comment]
@joecip Hi!
can you update package to v 1.9.8? it's must be working now :)

**Comment by joecip** [comment]
> @joecip Hi!
> can you update package to v 1.9.8? it's must be working now :)

Awesome. Thanks!
